#include "../include/integer.h"

#ifndef KEYBOARD_H
#define KEYBOARD_H

typedef enum {
    KEY_NOTHING, 
    KEY_ESCAPE,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    KEY_0,
    KEY_SUB,
    KEY_EQ,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_Q,
    KEY_W,
    KEY_E,
    KEY_R,
    KEY_T,
    KEY_Y,
    KEY_U,
    KEY_I,
    KEY_O,
    KEY_P,
    KEY_LBRACKET,
    KEY_RBRACKET,
    KEY_ENTER,
    KEY_CONTROL,
    KEY_A,
    KEY_S,
    KEY_D,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_SEMICOLON,
    KEY_SINGLE_QUOTE,
    KEY_BACK_TICK,
    KEY_SHIFT,
    KEY_ANTISLASH,
    KEY_Z,
    KEY_X,
    KEY_C,
    KEY_V,
    KEY_B,
    KEY_N,
    KEY_M,
    KEY_COMMA,
    KEY_DOT,
    KEY_SLASH,
    UNDEFINED4, // RSHIFT
    KEY_KEYPAD_STAR,
    KEY_ALT,
    KEY_SPACE,
    KEY_CAPS_LOCK,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_NUMBER_LOCK,
    KEY_SCROLL_LOCK, 
    KEY_KEYPAD_7, 
    KEY_KEYPAD_8, 
    KEY_KEYPAD_9, 
    KEY_KEYPAD_SUB,
    KEY_KEYPAD_4,
    KEY_KEYPAD_5,
    KEY_KEYPAD_6,
    KEY_KEYPAD_ADD,
    KEY_KEYPAD_1,
    KEY_KEYPAD_2,
    KEY_KEYPAD_3,
    KEY_KEYPAD_0, 
    KEY_KEYPAD_DOT, 
    UNDEFINED1,
    UNDEFINED2,
    UNDEFINED3,
    KEY_F11,
    KEY_F12,
    KEY_ARROW_UP,
    KEY_ARROW_DOWN,
    KEY_ARROW_LEFT,
    KEY_ARROW_RIGHT,
    KEY_DELETE
} Keys;
typedef enum {
    PRESSED,
    RELEASED
} State;
typedef struct {
    Keys key;
    State state;
} Key;
void keyboard_init(void);
Key keyboard_get_current_key(void);

#endif